### ISSUE TITLE
have a problem in chrome

### ISSUE THREAD

**Issue by taha-deris** [matthias-vogt/legitRipple.js#12]
my site have a problem with this plugin in chrome, after update the chrome browser today.
http://demo.interface.club/limitless/layout_1/RTL/material/index.html
you can see the problem in this link .
when click on the  links and buttons that have legitRipple enabled.

**Comment by juni-vogt** [comment]
What problem exactly do you mean? Everything worked smoothly for me.
I tested clicking the sidebar-toggle with 5x CPU throttling in Canary and got ~20fps though (unlike in the legitRipple demos).
If the ripples are stuttering for you then that's probably because the page is very resource intensive and not very performant. It should get better when you remove some of the components.

**Comment by taha-deris** [comment]
checkout this video to see the problem, 
http://sendvid.com/p2ri3919
thanks you.
