### ISSUE TITLE
Persistent ripple animation.

### ISSUE THREAD

**Issue by ivan-avalos** [matthias-vogt/legitRipple.js#21]
Hello, there!
I just wanted to know how could I tweak your plugin to change the background colour with each click and avoid fading the ripple. I managed to stop the fade, but the ripple is still disappearing and I can't figure out which part of the code or CSS makes it disappear.
I'm doing an application called [Colour Flow](https://github.com/ivan-avalos/ColourFlow-iOS), which requires that effect. Please help me!
I would really appreciate your help, my dear friend.

**Comment by juni-vogt** [comment]
Thanks for your interest in the plugin :) Sorry that I didn't see your issue before.

A ripple  element disappears because its CSS transition is finished and thus the JS Code removes it. You can hack around this by making the ripple's opacity transition very long. `.legitRipple-ripple { transition-duration: .2s, 999999s; } ` where the `.2s` regulates the width and the `999999s` regulates the opacity.
