### ISSUE TITLE
Make ripple effect more like material design 

### ISSUE THREAD

**Issue by Posandu** [matthias-vogt/legitRipple.js#23]
Great framework ! , Make ripple effect more like material design see this https://material-components.github.io/material-components-web-catalog/#/component/ripple

**Comment by juni-vogt** [comment]
Thanks for the issue! The main feature of this library is to make ripples that scale with respect to the click position in the parent element, as Android was using a lot a few years ago. This is why the library was named _legit_ ripple, because most other libraries used a simpler implementation, where ripples scale evenly.
Nowadays Android seems to be using this simpler implementation as well. You can achieve this using the `scaleMode: false` option. But I wouldn't make this the default because I think it is boring.
