### ISSUE TITLE
What is the logic behind the ripple effect ? 

### ISSUE THREAD

**Issue by Posandu** [matthias-vogt/legitRipple.js#24]
What is the logic behind the ripple effect ? how did you created the fancy border radius ?

**Comment by juni-vogt** [comment]
Hi thanks for asking :) I don't know what you mean with the fancy border radius.

Basically, when you click a ripple container (that is a container element which should have ripples when clicked):

1. a `<span class="ripple">` gets added to the element. This element is styled to look like a circle with `width: 0` and `transition: width 1s` or something.
2. the JS sets the width of the circle to be larger than the ripple element, and the `<span>` transitions/animates to the larger width, making the ripple appear to be growing
3. when the mouse is released (that is on `mouseup`) the `transition-duration` is decreased so that the `<span>`'s width transition speeds up

The ripples with `scaleMode = "proportional"` are basically the same. But they also have a `transition` from one `transform: translate(…)` to another `transform: translate(…)` that makes them appear to move from one place to the other.
