### ISSUE TITLE
Spam clicking causes "stuck" ripples (only on inline-block elements as far as I know)

### ISSUE THREAD

**Issue by CKH4** [matthias-vogt/legitRipple.js#6]

**Comment by juni-vogt** [comment]
I think I fixed the bug, please tell me if you can still produce it.
Seems like you were able to click more rapidly than 20ms :D
Because of this issue, I re-wrote the [transition-duration changing bit](https://github.com/matthias-vogt/legitRipple.js/blob/gh-pages/js/ripple.js#L249-L279) and now we can do cool stuff like this: [http://codepen.io/matze/pen/PPJxyr](http://codepen.io/matze/pen/PPJxyr), which wasn't possible before.
Thanks for submitting!
